services:
  sbsubs:
    # image: handysun/sbsubs:latest
    build:
        .
    container_name: sbsubs
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
    restart: no
